services:
  packet_publisher:
    build: ./
    ports:
      - "${UDP_PORT}:${UDP_PORT}/udp"
    command: ros2 run asv_sensors packet_publisher --ros-args -p ip_address:=${IP_ADDRESS} -p udp_port:=${UDP_PORT} --ros-args --log-level ${SENSOR_DRIVERS_LOG_LEVEL}

  imu_sensor_driver:
    build: ./
    command: ros2 run asv_sensors imu_sensor_driver --ros-args --log-level ${SENSOR_DRIVERS_LOG_LEVEL}

  power_level_sensor_driver:
    build: ./
    command: ros2 run asv_sensors power_level_sensor_driver  --ros-args --log-level ${SENSOR_DRIVERS_LOG_LEVEL}
  
  attitude_sensor_driver:
    build: ./
    command: ros2 run asv_sensors attitude_sensor_driver --ros-args --log-level ${SENSOR_DRIVERS_LOG_LEVEL}

  gps_sensor_driver:
    build: ./
    command: ros2 run asv_sensors gps_sensor_driver --ros-args --log-level ${SENSOR_DRIVERS_LOG_LEVEL}
