services:
  # ROSBAG Recorder
  rosbag_recorder:
    build: ./
    command: bash -c "ros2 bag record -a -o /root/rosbags/$(date +%Y%m%d_%H%M%S) --max-bag-duration 1800 --compression-mode file --compression-format zstd"
    volumes:
      - ./.rosbags:/root/rosbags

  # Sensor Drivers
  packet_publisher:
    build: ./
    ports:
      - "${UDP_PORT}:${UDP_PORT}/udp"
    command: ros2 run asv_sensors packet_publisher --ros-args -p ip_address:=${IP_ADDRESS} -p udp_port:=${UDP_PORT} --ros-args --log-level ${SENSOR_DRIVERS_LOG_LEVEL}

# Control Nodes
  asv_ergo_control:
    build: ./
    command: ros2 run asv_controller asv_ergo_control  --ros-args --log-level ${SENSOR_DRIVERS_LOG_LEVEL}
    volumes:
      - ./.jld2/:/root/jld2_files
      - ./.images/:/root/images
      - ./.julia:/root/.julia

  transect_control:
    build: ./
    command: ros2 run asv_controller transect_control  --ros-args --log-level ${SENSOR_DRIVERS_LOG_LEVEL}
    volumes:
      - ./.jld2/:/root/jld2_files
      - ./.images/:/root/images
      - ./.julia:/root/.julia

  q_map_pub:
    build: ./
    command: ros2 run asv_controller q_map_pub  --ros-args --log-level ${SENSOR_DRIVERS_LOG_LEVEL}
    volumes:
      - ./.images/:/root/images
      - ./.julia:/root/.julia

  target_q_map_pub:
    build: ./
    command: ros2 run asv_controller target_q_map_pub  --ros-args --log-level ${SENSOR_DRIVERS_LOG_LEVEL}
    volumes:
      - ./.images/:/root/images
      - ./.julia:/root/.julia

  w_hat_pub:
    build: ./
    command: ros2 run asv_controller w_hat_pub  --ros-args --log-level ${SENSOR_DRIVERS_LOG_LEVEL}
    volumes:
      - ./.images/:/root/images
      - ./.julia:/root/.julia

  command_publisher:
    build: ./
    network_mode: "host"
    command: ros2 run asv_sensors control_command_publisher --ros-args -p ip_address:=${BOAT_IP} -p udp_port:=${UDP_PORT} --ros-args --log-level ${SENSOR_DRIVERS_LOG_LEVEL}
    volumes:
      - ./.julia:/root/.julia

# Foxglove Bridge
  foxglove_bridge:
    build:
      dockerfile: ./Dockerfile.foxglove
    ports:
      - "8765:8765"

# Synthetic Data Publisher
  synth_data:
    build: ./
    command: ros2 run asv_controller synthetic_data_pub  --ros-args --log-level ${SENSOR_DRIVERS_LOG_LEVEL}
    volumes:
      - ./.julia:/root/.julia
