services:
  julia_test:
    build: ./
    command: ros2 run asv_controller julia_publisher  --ros-args --log-level ${SENSOR_DRIVERS_LOG_LEVEL}
  asv_ergo_control:
    build: ./
    volumes:
      - ./.julia:/root/.julia
    command: ros2 run asv_controller asv_ergo_control  --ros-args --log-level ${SENSOR_DRIVERS_LOG_LEVEL}
  param_estimator:
    build: ./
    command: ros2 run asv_controller param_estimator --ros-args --log-level ${SENSOR_DRIVERS_LOG_LEVEL}