# current timestamp for message
std_msgs/Header header
# latitude in radians
float64 latitude  
# longitude in radians
float64 longitude
# speed in knots towards target (always positive)
float32 kts
# heading towards target (always positive)
float32 heading
# current speed in knots (always positive)
float32 current_kts
# heading (always positive)
float32 current_heading
# wind speed in knots (always positive)
float32 wind_kts
# wind heading (always positive)
float32 wind_heading