# timestamp for this message
std_msgs/Header header
# current pitch in degrees
float32 pitch
# minimum pitch in degrees
float32 min_pitch
# maximum pitch in degrees
float32 max_pitch
# current roll in degrees
float32 roll
# minimum roll in degrees
float32 min_roll
# maximum roll in degrees
float32 max_roll
# current heading in degrees (always positive)
float32 heading
# minimum heading in degrees (always positive)
float32 min_heading
# maximum heading in degrees (always positive)
float32 max_heading